# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# Check these on https://fabricmc.net/develop and select the 26.1 snapshot manually
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.4.7-26.1
maven_group=dbrighthd.elytratrails
archives_base_name=elytratrails

# Dependencies
fabric_api_version=0.144.3+26.1
modmenu_version=18.0.0-alpha.6
cloth_version=26.1.154
iris_version=1.10.7+26.1-fabric
emf_version=3.0.14-fabric-26.1
etf_version=7.0.11-fabric-26.1
cpm_version=26.1v0.6.25a-fabric