# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# Check these on https://fabricmc.net/develop and select the 26.1 snapshot manually
minecraft_version=26.1-rc-2
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.4.3dev26.1
maven_group=dbrighthd.elytratrails
archives_base_name=elytratrails

# Dependencies
fabric_api_version=0.143.15+26.1
modmenu_version=18.0.0-alpha.6
cloth_version=21.11.153+fabric
iris_version=1.10.7+26.1-fabric