# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# Check these on https://fabricmc.net/develop and select the 26.1 snapshot manually
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.6.0-26.2
maven_group=dbrighthd.elytratrails
archives_base_name=elytratrails

# Dependencies
fabric_api_version=0.156.0+26.2
modmenu_version=20.0.0-beta.2
cloth_version=26.1.154
iris_version=1.11.1+26.2-fabric
emf_version=3.3.2-fabric-26.2
etf_version=7.2-fabric-26.2
cpm_version=26.2v0.6.26b-fabric
flashback_version=0.41.1